# Generated by Django 5.2.12 on 2026-05-12 12:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('compte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='N° de réservation')),
                ('date_visite', models.DateField(verbose_name='Date de visite')),
                ('heure_visite', models.TimeField(blank=True, null=True, verbose_name='Heure de visite')),
                ('nb_adultes', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Nombre d'adultes")),
                ('nb_enfants', models.PositiveSmallIntegerField(default=0, verbose_name="Nombre d'enfants")),
                ('date_arrivee', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée (hébergement)")),
                ('date_depart', models.DateField(blank=True, null=True, verbose_name='Date de départ (hébergement)')),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant total (FCFA)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('notes_touriste', models.TextField(blank=True, help_text='Demandes spéciales, allergies, etc.', verbose_name='Notes du touriste')),
                ('date_confirmation', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('date_annulation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('motif_annulation', models.TextField(blank=True, verbose_name="Motif d'annulation")),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='compte.guide', verbose_name='Guide (optionnel)')),
                ('hebergement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='catalogue.hebergement', verbose_name='Hébergement (optionnel)')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='catalogue.sitetouristique', verbose_name='Site touristique')),
                ('touriste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='compte.touriste', verbose_name='Touriste')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('type_service', models.CharField(choices=[('visite', 'Entrée au site'), ('hebergement', 'Hébergement'), ('guide', 'Services de guide'), ('supplement', 'Supplément')], max_length=20, verbose_name='Type de service')),
                ('designation', models.CharField(help_text="Ex: 'Entrée adulte - Plages de Kribi'", max_length=200, verbose_name='Désignation')),
                ('quantite', models.PositiveSmallIntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sous-total (FCFA)')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='reservation.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Ligne de réservation',
                'verbose_name_plural': 'Lignes de réservation',
                'ordering': ['reservation', 'type_service'],
            },
        ),
        migrations.CreateModel(
            name='BonReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('qr_code_data', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Données du QR Code')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/%Y/%m/', verbose_name='Image QR Code')),
                ('pdf_fichier', models.FileField(blank=True, null=True, upload_to='bons/%Y/%m/', verbose_name='Fichier PDF')),
                ('est_utilise', models.BooleanField(default=False, help_text="Coché quand le QR a été scanné à l'entrée", verbose_name='Utilisé')),
                ('date_utilisation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'utilisation (scan)")),
                ('scanne_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_scannes', to=settings.AUTH_USER_MODEL, verbose_name='Scanné par')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bon', to='reservation.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Bon de réservation',
                'verbose_name_plural': 'Bons de réservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['touriste', '-date_visite'], name='reservation_tourist_7b3b97_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['site', 'date_visite'], name='reservation_site_id_9e0ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['statut', 'date_visite'], name='reservation_statut_aea19e_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['numero'], name='reservation_numero_f8fd52_idx'),
        ),
        migrations.AddIndex(
            model_name='bonreservation',
            index=models.Index(fields=['qr_code_data'], name='reservation_qr_code_f9e0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='bonreservation',
            index=models.Index(fields=['est_utilise'], name='reservation_est_uti_8d1bd0_idx'),
        ),
    ]
