# Generated by Django 5.2.12 on 2026-06-05 08:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_refus',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de refus'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='frais_annulation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Frais d'annulation appliqués (FCFA)"),
        ),
        migrations.AddField(
            model_name='reservation',
            name='motif_refus',
            field=models.TextField(blank=True, verbose_name='Motif du refus'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('confirmee', 'Confirmée'), ('refusee', 'Refusée par le gestionnaire'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
