# Generated by Django 5.2.12 on 2026-05-23 08:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyenPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('libelle', models.CharField(max_length=80, unique=True, verbose_name='Libellé')),
                ('code', models.CharField(help_text="Ex: 'mtn_momo', 'orange_money', 'visa', 'cash'", max_length=30, unique=True, verbose_name='Code interne')),
                ('type', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('carte_bancaire', 'Carte bancaire'), ('cash', "Espèces (à l'arrivée)"), ('virement', 'Virement bancaire')], max_length=20, verbose_name='Type')),
                ('provider', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('manuel', 'Manuel')], max_length=30, verbose_name='Fournisseur (API)')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='Icône (chemin ou nom)')),
                ('description', models.TextField(blank=True, verbose_name="Description (affichée à l'utilisateur)")),
                ('instructions', models.TextField(blank=True, verbose_name="Instructions d'utilisation")),
                ('devises_supportees', models.JSONField(default=list, help_text='Format: ["XAF", "EUR", "USD"]', verbose_name='Devises supportées')),
                ('montant_min', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, verbose_name='Montant minimum (FCFA)')),
                ('montant_max', models.DecimalField(decimal_places=2, default=Decimal('5000000.00'), max_digits=12, verbose_name='Montant maximum (FCFA)')),
                ('frais_pourcentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ex: 1.5 pour 1.5% de frais', max_digits=5, verbose_name='Frais en pourcentage (%)')),
                ('frais_fixe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Frais fixe (FCFA)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Moyen de paiement',
                'verbose_name_plural': 'Moyens de paiement',
                'ordering': ['ordre_affichage', 'libelle'],
                'indexes': [models.Index(fields=['est_actif', 'ordre_affichage'], name='paiements_m_est_act_e57885_idx')],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(choices=[('paiement', 'Paiement'), ('remboursement', 'Remboursement')], default='paiement', max_length=20, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('devise', models.CharField(default='XAF', max_length=5, verbose_name='Devise')),
                ('montant_devise_origine', models.DecimalField(blank=True, decimal_places=2, help_text='Pour les paiements en EUR/USD (touristes étrangers)', max_digits=12, null=True, verbose_name="Montant en devise d'origine")),
                ('taux_change', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Taux de change appliqué')),
                ('statut', models.CharField(choices=[('initie', 'Initié'), ('en_cours', 'En cours de traitement'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('annule', 'Annulé'), ('rembourse', 'Remboursé')], default='initie', max_length=20, verbose_name='Statut')),
                ('reference_externe', models.CharField(blank=True, db_index=True, help_text='ID retourné par MTN MoMo / Orange Money / Stripe', max_length=100, verbose_name='Référence externe')),
                ('reference_interne', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence interne')),
                ('numero_telephone', models.CharField(blank=True, help_text='Format: 237 6XX XX XX XX', max_length=20, verbose_name='N° téléphone (Mobile Money)')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date du paiement')),
                ('date_remboursement', models.DateTimeField(blank=True, null=True, verbose_name='Date du remboursement')),
                ('date_echec', models.DateTimeField(blank=True, null=True, verbose_name="Date de l'échec")),
                ('motif_echec', models.TextField(blank=True, verbose_name="Motif d'échec")),
                ('callback_data', models.JSONField(blank=True, default=dict, help_text="Réponse brute de l'API de paiement", verbose_name='Données du callback')),
                ('moyen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='paiements.moyenpaiement', verbose_name='Moyen de paiement')),
                ('paiement_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='paiements.paiement', verbose_name='Paiement original (si remboursement)')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='reservation.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reservation', 'statut'], name='paiements_p_reserva_aafb8f_idx'), models.Index(fields=['statut', '-created_at'], name='paiements_p_statut_223bec_idx'), models.Index(fields=['reference_externe'], name='paiements_p_referen_d444c0_idx'), models.Index(fields=['reference_interne'], name='paiements_p_referen_5a1838_idx')],
            },
        ),
    ]
