# Generated by Django 5.2.12 on 2026-05-12 12:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom de la région')),
                ('code', models.CharField(choices=[('AD', 'Adamaoua'), ('CE', 'Centre'), ('ES', 'Est'), ('EN', 'Extrême-Nord'), ('LT', 'Littoral'), ('NO', 'Nord'), ('NW', 'Nord-Ouest'), ('OU', 'Ouest'), ('SU', 'Sud'), ('SW', 'Sud-Ouest')], help_text='Code ISO à 2 lettres', max_length=5, unique=True, verbose_name='Code région')),
                ('chef_lieu', models.CharField(help_text='Capitale administrative de la région', max_length=80, verbose_name='Chef-lieu')),
                ('description', models.TextField(blank=True, help_text='Présentation des attraits touristiques de la région', verbose_name='Description touristique')),
                ('image', models.ImageField(blank=True, null=True, upload_to='regions/', verbose_name='Image représentative')),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('ville', models.CharField(help_text='Ex: Kribi, Yaoundé, Douala, Limbé', max_length=80, verbose_name='Ville')),
                ('quartier', models.CharField(blank=True, help_text='Ex: Bastos, Bonanjo, Akwa', max_length=80, verbose_name='Quartier')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse détaillée')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Coordonnée GPS (format décimal, ex: 3.848)', max_digits=9, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Coordonnée GPS (format décimal, ex: 11.502)', max_digits=9, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude')),
                ('point_repere', models.CharField(blank=True, help_text="Ex: 'À 200m de l'hôtel Mont Fébé'", max_length=200, verbose_name='Point de repère')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Localisations', to='Localisations.region', verbose_name='Région')),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
                'ordering': ['region__nom', 'ville'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='localisatio_latitud_d064b2_idx'), models.Index(fields=['region', 'ville'], name='localisatio_region__3a7495_idx')],
            },
        ),
    ]
