# Generated by Django 5.2.12 on 2026-05-23 08:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('libelle', models.CharField(max_length=60, unique=True, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, help_text="Nom d'icône Tabler/FontAwesome (ex: 'mountain', 'beach')", max_length=50, verbose_name='Icône')),
                ('couleur', models.CharField(default='#15803D', help_text="Code hexadécimal pour l'affichage (ex: '#15803D')", max_length=7, verbose_name='Couleur')),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=0, help_text='Plus le nombre est petit, plus la catégorie apparaît en premier', verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre_affichage', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('hotel', 'Hôtel'), ('lodge', 'Lodge'), ('camping', 'Camping'), ('gite', 'Gîte'), ('auberge', 'Auberge'), ('appartement', 'Appartement')], max_length=20, verbose_name='Type')),
                ('nb_chambres', models.PositiveSmallIntegerField(default=1, verbose_name='Nombre de chambres')),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par nuit (FCFA)')),
                ('etoiles', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Étoiles (1-5)')),
                ('services', models.JSONField(blank=True, default=list, help_text='Format: ["wifi", "piscine", "restaurant", "climatisation"]', verbose_name='Services proposés')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hebergements/%Y/%m/', verbose_name='Photo principale')),
                ('est_disponible', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Hébergement',
                'verbose_name_plural': 'Hébergements',
                'ordering': ['site', '-etoiles', 'prix_nuit'],
            },
        ),
        migrations.CreateModel(
            name='PhotoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('image', models.ImageField(upload_to='sites/%Y/%m/', verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('est_principale', models.BooleanField(default=False, help_text='Photo affichée dans les listings', verbose_name='Photo principale')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Photo de site',
                'verbose_name_plural': 'Photos de sites',
                'ordering': ['site', 'ordre', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Association site-tag',
                'verbose_name_plural': 'Associations site-tag',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name='Libellé')),
                ('categorie_tag', models.CharField(blank=True, help_text="Ex: 'ambiance', 'public-cible', 'saison'", max_length=50, verbose_name='Catégorie du tag')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('date', models.DateField(verbose_name='Date')),
                ('places_restantes', models.PositiveIntegerField(default=0, verbose_name='Places restantes')),
                ('est_ferme', models.BooleanField(default=False, help_text='Coché pour les jours fériés ou fermetures exceptionnelles', verbose_name='Fermé ce jour-là')),
                ('tarif_special', models.DecimalField(blank=True, decimal_places=2, help_text='Tarif promotionnel ou saisonnier (sinon tarif normal du site)', max_digits=10, null=True, verbose_name='Tarif spécial (FCFA)')),
                ('hebergement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='catalogue.hebergement', verbose_name='Hébergement')),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SiteTouristique',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du site')),
                ('slug', models.SlugField(help_text='Ex: plages-de-kribi (généré automatiquement)', max_length=200, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('description_courte', models.CharField(blank=True, help_text='Affichée dans les listings (max 250 caractères)', max_length=250, verbose_name='Description courte')),
                ('type', models.CharField(choices=[('public', 'Public'), ('prive', 'Privé'), ('mixte', 'Mixte')], default='public', max_length=20, verbose_name='Type')),
                ('tarif_adulte', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif adulte (FCFA)')),
                ('tarif_enfant', models.DecimalField(decimal_places=2, help_text='Tarif pour les moins de 12 ans', max_digits=10, verbose_name='Tarif enfant (FCFA)')),
                ('horaires_ouverture', models.JSONField(blank=True, default=dict, help_text='Format: {"lundi": "08:00-17:00", "mardi": "08:00-17:00"}', verbose_name="Horaires d'ouverture")),
                ('capacite_max', models.PositiveIntegerField(default=100, help_text='Nombre maximum de visiteurs par jour', verbose_name='Capacité maximum')),
                ('duree_visite_moyenne', models.PositiveIntegerField(default=120, verbose_name='Durée moyenne de visite (minutes)')),
                ('accessibilite_pmr', models.BooleanField(default=False, verbose_name='Accessible aux PMR')),
                ('est_publie', models.BooleanField(default=False, help_text="Un site doit être validé avant d'être publié", verbose_name='Publié')),
                ('note_moyenne', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Note moyenne (sur 5)')),
                ('nombre_avis', models.PositiveIntegerField(default=0, verbose_name="Nombre d'avis")),
                ('nombre_vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='catalogue.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Site touristique',
                'verbose_name_plural': 'Sites touristiques',
                'ordering': ['-created_at'],
            },
        ),
    ]
