# Generated by Django 5.2.12 on 2026-05-23 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('compte', '0001_initial'),
        ('localisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetouristique',
            name='gestionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='compte.gestionnaire', verbose_name='Gestionnaire'),
        ),
        migrations.AddField(
            model_name='sitetouristique',
            name='localisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='site', to='localisation.localisation', verbose_name='Localisation'),
        ),
        migrations.AddField(
            model_name='sitetag',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.sitetouristique', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='photosite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalogue.sitetouristique', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hebergements', to='catalogue.sitetouristique', verbose_name='Site associé'),
        ),
        migrations.AddField(
            model_name='disponibilite',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='catalogue.sitetouristique', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='sitetouristique',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sites', through='catalogue.SiteTag', to='catalogue.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='sitetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.tag', verbose_name='Tag'),
        ),
        migrations.AddIndex(
            model_name='photosite',
            index=models.Index(fields=['site', 'est_principale'], name='catalogue_p_site_id_fa8317_idx'),
        ),
        migrations.AddIndex(
            model_name='hebergement',
            index=models.Index(fields=['site', 'est_disponible'], name='catalogue_h_site_id_3393b2_idx'),
        ),
        migrations.AddIndex(
            model_name='hebergement',
            index=models.Index(fields=['type'], name='catalogue_h_type_400a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilite',
            index=models.Index(fields=['site', 'date'], name='catalogue_d_site_id_526ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilite',
            index=models.Index(fields=['hebergement', 'date'], name='catalogue_d_heberge_4b833b_idx'),
        ),
        migrations.AddConstraint(
            model_name='disponibilite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hebergement__isnull', True), ('site__isnull', False)), models.Q(('hebergement__isnull', False), ('site__isnull', True)), _connector='OR'), name='disponibilite_site_ou_hebergement'),
        ),
        migrations.AddConstraint(
            model_name='disponibilite',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('site', 'date'), name='unique_disponibilite_site_date'),
        ),
        migrations.AddConstraint(
            model_name='disponibilite',
            constraint=models.UniqueConstraint(condition=models.Q(('hebergement__isnull', False)), fields=('hebergement', 'date'), name='unique_disponibilite_hebergement_date'),
        ),
        migrations.AddIndex(
            model_name='sitetouristique',
            index=models.Index(fields=['est_publie', '-note_moyenne'], name='catalogue_s_est_pub_d23539_idx'),
        ),
        migrations.AddIndex(
            model_name='sitetouristique',
            index=models.Index(fields=['categorie', 'est_publie'], name='catalogue_s_categor_1b529d_idx'),
        ),
        migrations.AddIndex(
            model_name='sitetouristique',
            index=models.Index(fields=['slug'], name='catalogue_s_slug_a7c0a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sitetag',
            unique_together={('site', 'tag')},
        ),
    ]
