# Generated by Django 5.2.12 on 2026-06-01 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoHebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('image', models.ImageField(upload_to='hebergements/%Y/%m/', verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('est_principale', models.BooleanField(default=False, help_text="Si coché, devient la photo de couverture de l'hébergement.", verbose_name='Photo principale')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('hebergement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalogue.hebergement', verbose_name='Hébergement')),
            ],
            options={
                'verbose_name': "Photo d'hébergement",
                'verbose_name_plural': "Photos d'hébergements",
                'ordering': ['hebergement', 'ordre', 'created_at'],
                'indexes': [models.Index(fields=['hebergement', 'est_principale'], name='catalogue_p_heberge_6738d5_idx')],
            },
        ),
    ]
