# Generated by Django 5.2.12 on 2026-05-12 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferencesNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('reservations_email', models.BooleanField(default=True, verbose_name='Recevoir par email les notifications de réservation')),
                ('reservations_sms', models.BooleanField(default=False, verbose_name='Recevoir par SMS les notifications de réservation')),
                ('paiements_email', models.BooleanField(default=True, verbose_name='Recevoir par email les notifications de paiement')),
                ('paiements_sms', models.BooleanField(default=True, verbose_name='Recevoir par SMS les notifications de paiement')),
                ('newsletter', models.BooleanField(default=False, verbose_name='Recevoir la newsletter mensuelle')),
                ('promotions', models.BooleanField(default=False, verbose_name='Recevoir les promotions et offres spéciales')),
                ('notifications_dashboard', models.BooleanField(default=True, verbose_name='Recevoir les notifications sur le dashboard')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_notification', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférences de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('corps', models.TextField(verbose_name='Corps du message')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='messages/%Y/%m/', verbose_name='Pièce jointe')),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('lu', 'Lu'), ('repondu', 'Répondu')], default='envoye', max_length=20, verbose_name='Statut')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
                ('message_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='notifications.message', verbose_name='Message parent (si réponse)')),
                ('reservations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reservations.reservations', verbose_name='Réservation liée (optionnel)')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinataire', 'statut'], name='notificatio_destina_498e40_idx'), models.Index(fields=['expediteur', '-created_at'], name='notificatio_expedit_d584b1_idx'), models.Index(fields=['destinataire', '-created_at'], name='notificatio_destina_7a9bda_idx'), models.Index(fields=['reservations', '-created_at'], name='notificatio_reserva_49e599_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('type', models.CharField(choices=[('res_creee', 'Réservation créée'), ('res_confirmee', 'Réservation confirmée'), ('res_annulee', 'Réservation annulée'), ('rappel_visite', 'Rappel de visite (24h avant)'), ('paiement_reussi', 'Paiement réussi'), ('paiement_echoue', 'Paiement échoué'), ('remboursement', 'Remboursement effectué'), ('avis_recu', 'Nouvel avis reçu'), ('avis_approuve', 'Votre avis a été approuvé'), ('reponse_gest', 'Réponse à votre avis'), ('compte_valide', 'Compte gestionnaire validé'), ('compte_rejete', 'Compte gestionnaire rejeté'), ('bienvenue', 'Message de bienvenue'), ('promotion', 'Promotion / Newsletter'), ('info', 'Information générale')], max_length=30, verbose_name='Type')),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Notification push'), ('in_app', 'Notification in-app (cloche)')], max_length=10, verbose_name="Canal d'envoi")),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('url_action', models.URLField(blank=True, help_text='Lien vers lequel rediriger lors du clic (ex: détails de la réservation)', max_length=500, verbose_name="URL d'action")),
                ('statut', models.CharField(choices=[('en_attente', "En attente d'envoi"), ('envoyee', 'Envoyée'), ('echec', "Échec d'envoi"), ('lue', 'Lue par le destinataire')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('motif_echec', models.TextField(blank=True, verbose_name="Motif d'échec")),
                ('metadonnees', models.JSONField(blank=True, default=dict, help_text='Données techniques (response ID du provider email/SMS, etc.)', verbose_name='Métadonnées')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('reservations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reservations.reservations', verbose_name='Réservation liée')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinataire', '-created_at'], name='notificatio_destina_2a7b0c_idx'), models.Index(fields=['destinataire', 'statut'], name='notificatio_destina_10ae3b_idx'), models.Index(fields=['statut', '-created_at'], name='notificatio_statut_168ad5_idx'), models.Index(fields=['canal', 'statut'], name='notificatio_canal_c02d88_idx')],
            },
        ),
    ]
