# Generated by Django 5.2.12 on 2026-05-12 12:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('compte', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1-5)')),
                ('titre', models.CharField(blank=True, max_length=150, verbose_name="Titre de l'avis")),
                ('commentaire', models.TextField(verbose_name='Commentaire')),
                ('note_accueil', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note Accueil')),
                ('note_proprete', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note Propreté')),
                ('note_rapport_qualite_prix', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note Rapport qualité/prix')),
                ('statut_moderation', models.CharField(choices=[('en_attente', 'En attente de modération'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('signale', 'Signalé par un utilisateur')], default='en_attente', max_length=20, verbose_name='Statut de modération')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('est_visible', models.BooleanField(default=False, verbose_name='Visible publiquement')),
                ('reponse_gestionnaire', models.TextField(blank=True, verbose_name='Réponse du gestionnaire')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de la réponse')),
                ('nombre_utiles', models.PositiveIntegerField(default=0, verbose_name='Nombre de "Utile" reçus')),
                ('nombre_signalements', models.PositiveIntegerField(default=0, verbose_name='Nombre de signalements')),
                ('reservations', models.OneToOneField(help_text="Garantit qu'un avis = une visite effective (anti-faux avis)", on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='reservations.reservations', verbose_name='Réservation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='catalogue.sitetouristique', verbose_name='Site')),
                ('touriste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to='compte.touriste', verbose_name='Touriste')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('note_personnelle', models.TextField(blank=True, help_text='Note privée du touriste (non visible publiquement)', verbose_name='Note personnelle')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajoute_aux_favoris_par', to='catalogue.sitetouristique', verbose_name='Site')),
                ('touriste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='compte.touriste', verbose_name='Touriste')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UtiliteAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('est_utile', models.BooleanField(default=True, help_text='True = utile, False = pas utile', verbose_name='Considéré comme utile')),
                ('avis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_utiles', to='reviews.avis', verbose_name='Avis')),
                ('touriste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_juges_utiles', to='compte.touriste', verbose_name='Touriste')),
            ],
            options={
                'verbose_name': "Vote d'utilité",
                'verbose_name_plural': "Votes d'utilité",
            },
        ),
        migrations.AddIndex(
            model_name='avis',
            index=models.Index(fields=['site', 'est_visible', '-created_at'], name='reviews_avi_site_id_803060_idx'),
        ),
        migrations.AddIndex(
            model_name='avis',
            index=models.Index(fields=['statut_moderation'], name='reviews_avi_statut__767976_idx'),
        ),
        migrations.AddIndex(
            model_name='avis',
            index=models.Index(fields=['touriste', '-created_at'], name='reviews_avi_tourist_02de87_idx'),
        ),
        migrations.AddIndex(
            model_name='favori',
            index=models.Index(fields=['touriste', '-created_at'], name='reviews_fav_tourist_2e8a65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favori',
            unique_together={('touriste', 'site')},
        ),
        migrations.AlterUniqueTogether(
            name='utiliteavis',
            unique_together={('avis', 'touriste')},
        ),
    ]
