# Generated by Django 5.2.12 on 2026-05-23 08:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('telephone', models.CharField(blank=True, help_text='Format international : +237 6XX XXX XXX', max_length=20, verbose_name='Téléphone')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/', verbose_name='Photo de profil')),
                ('type_user', models.CharField(choices=[('touriste', 'Touriste'), ('gestionnaire', 'Gestionnaire de site'), ('guide', 'Guide touristique'), ('admin', 'Administrateur')], default='touriste', max_length=20, verbose_name="Type d'utilisateur")),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('role', models.CharField(choices=[('super_admin', 'Super administrateur'), ('moderateur', 'Modérateur'), ('support', 'Support client')], default='moderateur', max_length=20, verbose_name='Rôle')),
                ('niveau_acces', models.PositiveSmallIntegerField(default=1, help_text='1 = basique, 5 = total', verbose_name="Niveau d'accès")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_admin', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
            },
        ),
        migrations.CreateModel(
            name='Gestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('entreprise', models.CharField(max_length=150, verbose_name="Nom de l'entreprise")),
                ('num_registre_commerce', models.CharField(help_text="N° d'identification légal de l'entreprise", max_length=50, unique=True, verbose_name='N° registre de commerce')),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut de validation')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif du rejet (si applicable)')),
                ('admin_valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestionnaires_valides', to='compte.administrateur', verbose_name='Admin valideur')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_gestionnaire', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Gestionnaire',
                'verbose_name_plural': 'Gestionnaires',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('tarif_journalier', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif journalier (FCFA)')),
                ('annees_experience', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('licence_pro', models.CharField(max_length=50, unique=True, verbose_name='N° licence professionnelle')),
                ('note_moyenne', models.FloatField(default=0.0, verbose_name='Note moyenne (sur 5)')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible pour de nouvelles missions')),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut de validation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_guide', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Guide touristique',
                'verbose_name_plural': 'Guides touristiques',
            },
        ),
        migrations.CreateModel(
            name='LangueGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(help_text='Ex: fr, en, es, de, ar', max_length=10, verbose_name='Code langue')),
                ('niveau', models.CharField(choices=[('basique', 'Basique'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('natif', 'Natif')], default='intermediaire', max_length=20, verbose_name='Niveau')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langues', to='compte.guide', verbose_name='Guide')),
            ],
            options={
                'verbose_name': 'Langue parlée par un guide',
                'verbose_name_plural': 'Langues parlées par les guides',
            },
        ),
        migrations.CreateModel(
            name='Touriste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('nationalite', models.CharField(default='Camerounaise', max_length=50, verbose_name='Nationalité')),
                ('cni_passeport', models.CharField(blank=True, help_text="Pour vérification à l'entrée des sites", max_length=30, verbose_name='N° CNI ou passeport')),
                ('type', models.CharField(choices=[('local', 'Touriste local'), ('etranger', 'Touriste étranger')], default='local', max_length=20, verbose_name='Type')),
                ('langue_pref', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue préférée')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('points_fidelite', models.PositiveIntegerField(default=0, verbose_name='Points de fidélité')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_touriste', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Touriste',
                'verbose_name_plural': 'Touristes',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='compte_user_email_2749a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['type_user'], name='compte_user_type_us_8dc3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='gestionnaire',
            index=models.Index(fields=['statut_validation'], name='compte_gest_statut__4a850c_idx'),
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['disponible'], name='compte_guid_disponi_028ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['-note_moyenne'], name='compte_guid_note_mo_90c579_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='langueguide',
            unique_together={('guide', 'langue')},
        ),
    ]
