# Generated by Django 5.2.12 on 2026-05-12 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Renseigné automatiquement à la création', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement à chaque save()', verbose_name='Date de modification')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('validate', 'Validation'), ('reject', 'Rejet'), ('payment', 'Paiement'), ('refund', 'Remboursement')], max_length=20, verbose_name="Type d'action")),
                ('ressource', models.CharField(help_text='Ex: SiteTouristique, Reservation, Paiement', max_length=100, verbose_name='Ressource concernée')),
                ('id_ressource', models.CharField(blank=True, max_length=100, verbose_name='ID de la ressource')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent du navigateur')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Données contextuelles au format JSON', verbose_name='Détails supplémentaires')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_auditl_created_1a76fa_idx'), models.Index(fields=['utilisateur', '-created_at'], name='core_auditl_utilisa_af8707_idx'), models.Index(fields=['ressource', 'id_ressource'], name='core_auditl_ressour_f88597_idx')],
            },
        ),
    ]
